# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fe7d5de5b93c0f0ba4d154e03e9a15ac2b706f65095535ae21422943a415fd290cf7d85d5b714ad3c45589997b44ce2b7c1aad0e4ac14abeabed30993417c59

test:
  secret_key_base: 06e633e35c893af010ea046e28c9b9497f2509cf375ffcedcd7bfbc98b51f69e7628f9c241ddfd922f2292c269406fafdf22ee3889010e56b0503c46dbd7c7f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
